---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        entry: |
          codespell -q 3 -f
          -S ".git,.github,*go.*,ttps/*"

  - repo: local
    hooks:
      - id: go-copyright
        name: Ensure all go files have the copyright header
        language: script
        entry: .hooks/go-copyright.sh
        files: '\.go$'

      - id: check-underscores-in-name
        name: Ensure all committed directories and YAML files are uniform
        language: script
        entry: .hooks/check-underscores-in-name.sh
