---
name: Pre-Commit
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  pre-commit:
    name: Update pre-commit hooks and run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Install pre-commit
        run: pip3 install pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
